namespace DeepDungeonTracker
{
    public enum Pomander
    {
        Safety,
        Sight,
        Strength,
        Steel,
        Affluence,
        Flight,
        Alteration,
        Purity,
        Fortune,
        Witching,
        Serenity,
        Rage,
        Lust,
        Intuition,
        Raising,
        Resolution,
        Frailty,
        Concealment,
        Petrification,
        InfernoMagicite,
        CragMagicite,
        VortexMagicite,
        ElderMagicite
    }
}